
package https.test_arriba_net_de.dispatcher;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "TenderCreationService", targetNamespace = "https://test.arriba-net.de/dispatcher.php?plugin=TenderCreationPlugin", wsdlLocation = "/test.wsdl")
public class TenderCreationService
    extends Service
{

    private final static URL TENDERCREATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException TENDERCREATIONSERVICE_EXCEPTION;
    private final static QName TENDERCREATIONSERVICE_QNAME = new QName("https://test.arriba-net.de/dispatcher.php?plugin=TenderCreationPlugin", "TenderCreationService");

    static {
        TENDERCREATIONSERVICE_WSDL_LOCATION = https.test_arriba_net_de.dispatcher.TenderCreationService.class.getResource("/test.wsdl");
        WebServiceException e = null;
        if (TENDERCREATIONSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/test.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        TENDERCREATIONSERVICE_EXCEPTION = e;
    }

    public TenderCreationService() {
        super(__getWsdlLocation(), TENDERCREATIONSERVICE_QNAME);
    }

    public TenderCreationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TENDERCREATIONSERVICE_QNAME, features);
    }

    public TenderCreationService(URL wsdlLocation) {
        super(wsdlLocation, TENDERCREATIONSERVICE_QNAME);
    }

    public TenderCreationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TENDERCREATIONSERVICE_QNAME, features);
    }

    public TenderCreationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TenderCreationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TenderCreationPort
     */
    @WebEndpoint(name = "TenderCreationPort")
    public TenderCreationPort getTenderCreationPort() {
        return super.getPort(new QName("https://test.arriba-net.de/dispatcher.php?plugin=TenderCreationPlugin", "TenderCreationPort"), TenderCreationPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TenderCreationPort
     */
    @WebEndpoint(name = "TenderCreationPort")
    public TenderCreationPort getTenderCreationPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://test.arriba-net.de/dispatcher.php?plugin=TenderCreationPlugin", "TenderCreationPort"), TenderCreationPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TENDERCREATIONSERVICE_EXCEPTION!= null) {
            throw TENDERCREATIONSERVICE_EXCEPTION;
        }
        return TENDERCREATIONSERVICE_WSDL_LOCATION;
    }

}
