
package localhost._4434.tender;

import jakarta.jws.Oneway;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "TenderCreationPort", targetNamespace = "http://localhost:4434/tender")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    localhost._4434.tender.ObjectFactory.class,
    org.xmlsoap.schemas.soap.encoding.ObjectFactory.class
})
public interface TenderCreationPort {


    /**
     * erstellt den Token, welcher als schneller Nachweis des Logins des Clients dient
     * 
     * @param vobagUser
     * @param hex
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "_getTokenVal", action = "http://localhost:4434/tender#_getTokenVal")
    @WebResult(partName = "return")
    public String getTokenVal(
        @WebParam(name = "Vobag_user", partName = "Vobag_user")
        Object vobagUser,
        @WebParam(name = "hex", partName = "hex")
        String hex);

    /**
     * @soap
     * 
     * @return
     *     returns localhost._4434.tender.ArrayOfUnclassifiedKeyValue
     */
    @WebMethod(action = "http://localhost:4434/tender#getVergabeordnungMapping")
    @WebResult(partName = "return")
    public ArrayOfUnclassifiedKeyValue getVergabeordnungMapping();

    /**
     * @soap
     * 
     * @return
     *     returns localhost._4434.tender.ArrayOfUnclassifiedKeyValue
     */
    @WebMethod(action = "http://localhost:4434/tender#showExportStatusValues")
    @WebResult(partName = "return")
    public ArrayOfUnclassifiedKeyValue showExportStatusValues();

    /**
     * @soap
     * 
     * @param params
     * @return
     *     returns localhost._4434.tender.SuccessfulBidderParams
     */
    @WebMethod(action = "http://localhost:4434/tender#getSuccessfulCompany")
    @WebResult(partName = "return")
    public SuccessfulBidderParams getSuccessfulCompany(
        @WebParam(name = "params", partName = "params")
        SuccessfulBidderSearchParams params);

    /**
     * @soap
     * 
     * @param params
     * @return
     *     returns localhost._4434.tender.TenderCreationStatus
     */
    @WebMethod(action = "http://localhost:4434/tender#updateSuccessfulCompany")
    @WebResult(partName = "return")
    public TenderCreationStatus updateSuccessfulCompany(
        @WebParam(name = "params", partName = "params")
        SuccessfulBidderParams params);

    /**
     * @soap
     * 
     * @param params
     * @return
     *     returns localhost._4434.tender.ArrayOfStatusResultData
     */
    @WebMethod(action = "http://localhost:4434/tender#getTenderExport")
    @WebResult(partName = "return")
    public ArrayOfStatusResultData getTenderExport(
        @WebParam(name = "params", partName = "params")
        ExportSearchValues params);

    /**
     * @soap
     * 
     * @param password
     * @param language
     * @param username
     * @return
     *     returns localhost._4434.tender.TenderCreationStatus
     */
    @WebMethod(action = "http://localhost:4434/tender#authenticate")
    @WebResult(partName = "return")
    public TenderCreationStatus authenticate(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "language", partName = "language")
        String language);

    /**
     * @soap
     * 
     * @param sessionId
     * @param namePart
     * @return
     *     returns localhost._4434.tender.ArrayOfCompanyReturn
     */
    @WebMethod(action = "http://localhost:4434/tender#bidderSearch")
    @WebResult(partName = "return")
    public ArrayOfCompanyReturn bidderSearch(
        @WebParam(name = "name_part", partName = "name_part")
        String namePart,
        @WebParam(name = "session_id", partName = "session_id")
        String sessionId);

    /**
     * @soap
     * 
     * @param nameAward
     * @param sessionId
     * @param namePrj
     * @return
     *     returns localhost._4434.tender.TenderCreationStatus
     */
    @WebMethod(action = "http://localhost:4434/tender#checkTenderNumber")
    @WebResult(partName = "return")
    public TenderCreationStatus checkTenderNumber(
        @WebParam(name = "_NameAward", partName = "_NameAward")
        String nameAward,
        @WebParam(name = "NamePrj", partName = "NamePrj")
        String namePrj,
        @WebParam(name = "session_id", partName = "session_id")
        String sessionId);

    /**
     * @soap
     * 
     * @param agLvId
     * @param token
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://localhost:4434/tender#releaseTNW")
    @WebResult(partName = "return")
    public boolean releaseTNW(
        @WebParam(name = "token", partName = "token")
        String token,
        @WebParam(name = "ag_lv_id", partName = "ag_lv_id")
        int agLvId);

    /**
     * @soap
     * 
     * @param stream
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://localhost:4434/tender#crypt")
    @WebResult(partName = "return")
    public String crypt(
        @WebParam(name = "stream", partName = "stream")
        String stream,
        @WebParam(name = "token", partName = "token")
        String token);

    /**
     * @soap
     * 
     * @param agLvId
     * @param token
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "finalFirm_approve", action = "http://localhost:4434/tender#finalFirm_approve")
    @WebResult(partName = "return")
    public boolean finalFirmApprove(
        @WebParam(name = "token", partName = "token")
        String token,
        @WebParam(name = "ag_lv_id", partName = "ag_lv_id")
        int agLvId);

    /**
     * @soap
     * 
     * @param agLvId
     * @param token
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://localhost:4434/tender#inviteBidders")
    @WebResult(partName = "return")
    public boolean inviteBidders(
        @WebParam(name = "token", partName = "token")
        String token,
        @WebParam(name = "ag_lv_id", partName = "ag_lv_id")
        int agLvId);

    /**
     * Selenium - Funktion
     * 
     * @param vobagUser
     * @param token
     */
    @WebMethod(action = "http://localhost:4434/tender#setVobagUser")
    @Oneway
    public void setVobagUser(
        @WebParam(name = "Vobag_user", partName = "Vobag_user")
        Object vobagUser,
        @WebParam(name = "token", partName = "token")
        String token);

    /**
     * für die Bookmark - Actions
     * 
     * @param projektId
     * @param agLvId
     * @param token
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://localhost:4434/tender#setLvId")
    @WebResult(partName = "return")
    public boolean setLvId(
        @WebParam(name = "ag_lv_id", partName = "ag_lv_id")
        int agLvId,
        @WebParam(name = "projekt_id", partName = "projekt_id")
        int projektId,
        @WebParam(name = "token", partName = "token")
        String token);

    /**
     * Selenium Funktion
     * 
     * @param vobagUser
     * @param addPaperBidders
     * @param agLvId
     * @param finishOpening
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://localhost:4434/tender#openingAction")
    @WebResult(partName = "return")
    public String openingAction(
        @WebParam(name = "ag_lv_id", partName = "ag_lv_id")
        int agLvId,
        @WebParam(name = "token", partName = "token")
        Object token,
        @WebParam(name = "add_paper_bidders", partName = "add_paper_bidders")
        Object addPaperBidders,
        @WebParam(name = "finish_opening", partName = "finish_opening")
        Object finishOpening,
        @WebParam(name = "Vobag_user", partName = "Vobag_user")
        Object vobagUser);

    /**
     * @soap
     * 
     * @param virtualVaId
     * @param sessionId
     * @return
     *     returns localhost._4434.tender.ArrayOfDateConfigReturn
     */
    @WebMethod(action = "http://localhost:4434/tender#getDatesConfig")
    @WebResult(partName = "return")
    public ArrayOfDateConfigReturn getDatesConfig(
        @WebParam(name = "virtual_va_id", partName = "virtual_va_id")
        int virtualVaId,
        @WebParam(name = "session_id", partName = "session_id")
        String sessionId);

    /**
     * @soap
     * 
     * @param sessionId
     * @return
     *     returns localhost._4434.tender.ArrayOfPublicProcurementLaw
     */
    @WebMethod(action = "http://localhost:4434/tender#getPublicProcurementLaw")
    @WebResult(partName = "return")
    public ArrayOfPublicProcurementLaw getPublicProcurementLaw(
        @WebParam(name = "session_id", partName = "session_id")
        String sessionId);

    /**
     * @soap
     * 
     * @param sessionId
     * @param vvId
     * @return
     *     returns localhost._4434.tender.ArrayOfTenderRegulation
     */
    @WebMethod(action = "http://localhost:4434/tender#getTenderRegulations")
    @WebResult(partName = "return")
    public ArrayOfTenderRegulation getTenderRegulations(
        @WebParam(name = "vv_id", partName = "vv_id")
        int vvId,
        @WebParam(name = "session_id", partName = "session_id")
        String sessionId);

    /**
     * @soap
     * 
     * @param sessionId
     * @param vvId
     * @return
     *     returns localhost._4434.tender.ArrayOfSpecificsPublicProcurementLaw
     */
    @WebMethod(action = "http://localhost:4434/tender#getSpecificPublicProcurementLaw")
    @WebResult(partName = "return")
    public ArrayOfSpecificsPublicProcurementLaw getSpecificPublicProcurementLaw(
        @WebParam(name = "vv_id", partName = "vv_id")
        int vvId,
        @WebParam(name = "session_id", partName = "session_id")
        String sessionId);

    /**
     * @nillable
     * 
     * @param area
     * @return
     *     returns localhost._4434.tender.ArrayOfVobagVergabeBez
     */
    @WebMethod(action = "http://localhost:4434/tender#getTenderLabelTemplates")
    @WebResult(partName = "return")
    public ArrayOfVobagVergabeBez getTenderLabelTemplates(
        @WebParam(name = "area", partName = "area")
        String area);

    /**
     * @soap
     * 
     * @param lots
     * @param virtualVaId
     * @param sessionId
     * @return
     *     returns localhost._4434.tender.ArrayOfTenderConfigFormsets
     */
    @WebMethod(action = "http://localhost:4434/tender#getFormsatzIds")
    @WebResult(partName = "return")
    public ArrayOfTenderConfigFormsets getFormsatzIds(
        @WebParam(name = "virtual_va_id", partName = "virtual_va_id")
        int virtualVaId,
        @WebParam(name = "lots", partName = "lots")
        boolean lots,
        @WebParam(name = "session_id", partName = "session_id")
        String sessionId);

    /**
     * @soap
     * 
     * @param virtualVaId
     * @param sessionId
     * @return
     *     returns localhost._4434.tender.ArrayOfRegulationDetail
     */
    @WebMethod(action = "http://localhost:4434/tender#getTenderRegulationDetails")
    @WebResult(partName = "return")
    public ArrayOfRegulationDetail getTenderRegulationDetails(
        @WebParam(name = "virtual_va_id", partName = "virtual_va_id")
        int virtualVaId,
        @WebParam(name = "session_id", partName = "session_id")
        String sessionId);

    /**
     * @soap
     * 
     * @return
     *     returns localhost._4434.tender.ArrayOfTenderConfigFederalStates
     */
    @WebMethod(action = "http://localhost:4434/tender#getFederalStates")
    @WebResult(partName = "return")
    public ArrayOfTenderConfigFederalStates getFederalStates();

    /**
     * @soap
     * 
     * @param tenderCreationObject
     * @return
     *     returns localhost._4434.tender.TenderCreationStatus
     */
    @WebMethod(action = "http://localhost:4434/tender#createTender")
    @WebResult(partName = "return")
    public TenderCreationStatus createTender(
        @WebParam(name = "TenderCreationObject", partName = "TenderCreationObject")
        TenderCreationObject tenderCreationObject);

    /**
     * @soap
     * 
     * @param token
     * @return
     *     returns localhost._4434.tender.InfosForContentXml
     */
    @WebMethod(action = "http://localhost:4434/tender#getTnwAddFilesData")
    @WebResult(partName = "return")
    public InfosForContentXml getTnwAddFilesData(
        @WebParam(name = "token", partName = "token")
        String token);

    /**
     * @soap
     * 
     * @param token
     * @return
     *     returns localhost._4434.tender.InfosForContentXml
     */
    @WebMethod(action = "http://localhost:4434/tender#getOfferDocInfos")
    @WebResult(partName = "return")
    public InfosForContentXml getOfferDocInfos(
        @WebParam(name = "token", partName = "token")
        String token);

    /**
     * generateTokenSession
     * 
     * @param vobagUser
     */
    @WebMethod(action = "http://localhost:4434/tender#generateTokenSession")
    @Oneway
    public void generateTokenSession(
        @WebParam(name = "Vobag_user", partName = "Vobag_user")
        Object vobagUser);

}
